### PR TITLE
Improve snippets

### PR DESCRIPTION
**Pull request by mkhl**
This change:
* defines shorter tab triggers:
    * A for Array
    * D for Dictionary
* defines more snippets:
    * S for Set, the type, analogous to Array and Dictionary
    * im for import statements

### CODE REVIEW

**Comment by jtbandes** [comment]
Why do we even have snippets for `Array<x>` and `Dictionary<x,x>` when the sugared forms `[x]` and `[x: x]` are usually preferred?

**Comment by mkhl** [comment]
I was wondering about that myself, but felt that a larger overhaul of the snippets might be in order anyway, given time and opportunity.

**Comment by infininight** [comment]
Don't have any comment on the snippet themselves, but not sold on the shorter triggers, doesn't seem to follow any sort of convention based on any of the existing snippet triggers for the bundle?

**Comment by jtbandes** [comment]
`im` seems reasonable to me, but I think we should just remove the Array/Dictionary ones. shift+S+tab is nearly the same number of keystrokes as Set<, so I don't think that one's really needed either.

**Comment by sorbits** [comment]
+1 for just removing the Array and Dictionary snippets.

The current form makes no sense (having to type out the full word) but 
if we shorten the triggers, I think we should come up with a convention, 
e.g. the Ruby bundle limits all triggers (more or less) to the first 3 
letters.

Related to the mentioned snippets, the class⇥ snippet seems either 
incomplete or somewhat useless, also, the common trigger for “class” 
is “cl⇥”.

**Pull request closed without merging**
